from pathlib import Path
from docx import Document


def generate_basic_report(athlete_name: str, video_info: dict, diagnosis_text: str, output_path: str = "data/reports/basic_report.docx") -> str:
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    doc = Document()
    doc.add_heading("Underwater Swimming Biomechanics Report", level=1)
    doc.add_heading("Athlete", level=2)
    doc.add_paragraph(f"Name: {athlete_name}")
    doc.add_heading("Video information", level=2)
    for key, value in video_info.items():
        doc.add_paragraph(f"{key}: {value}")
    doc.add_heading("Technical diagnosis", level=2)
    doc.add_paragraph(diagnosis_text)
    doc.add_heading("Note", level=2)
    doc.add_paragraph("This report is generated by SwimBiomech Analyst. MVP thresholds are preliminary and must be calibrated with swimming-specific data.")
    doc.save(output_path)
    return output_path
